# Generated by Django 4.2.20 on 2025-04-23 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentify', '0002_alter_agent_options_agent_is_public_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='workspace_agents',
            field=models.ManyToManyField(blank=True, help_text="Agents added to this user's workspace.", related_name='users_in_workspace', to='agentify.agent'),
        ),
    ]
