name: Django CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.10, 3.11] # Test against relevant Python versions

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      working-directory: ./backend # Adjust if structure differs
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        # Install dev dependencies if separated (e.g., pip install flake8 black)
    # - name: Lint with flake8 # Optional: Add linters
    #   working-directory: ./backend
    #   run: |
    #     flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    #     flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Run Tests (Placeholder - No tests yet in Sprint 0)
      working-directory: ./backend
      env: # Set dummy env vars for settings loading if needed
        SECRET_KEY: test_key
        DATABASE_URL: sqlite:///db.sqlite3 # Use SQLite for CI tests
        DEBUG: False
      run: |
        # python manage.py test # Uncomment when tests are added in Sprint 1
        echo "No tests configured yet."