# Generated by Django 4.2.20 on 2025-04-23 02:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agentify', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agent',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='agent',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Is this agent visible to everyone in the marketplace?'),
        ),
        migrations.AddField(
            model_name='agent',
            name='short_description',
            field=models.CharField(blank=True, help_text='A brief summary shown in list views.', max_length=255),
        ),
        migrations.AddField(
            model_name='agent',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly version of the name, auto-generated if left blank.', max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='creator',
            field=models.ForeignKey(blank=True, help_text='The user who created this agent.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_agents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='agent',
            name='description',
            field=models.TextField(blank=True, help_text='A detailed description of what the agent does.'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='name',
            field=models.CharField(help_text='The unique name of the AI agent.', max_length=100, unique=True),
        ),
    ]
