# Generated by Django 4.2.20 on 2025-04-23 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentify', '0002_alter_agent_options_agent_is_public_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='illustration',
            field=models.CharField(blank=True, help_text="Filename of the illustration in static/images/ (e.g., 'tool_icon.png')", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='tier',
            field=models.CharField(choices=[('basic', 'Basic'), ('advanced', 'Advanced')], default='basic', help_text='Access tier for this agent.', max_length=20),
        ),
    ]
