# Generated by Django 4.2.20 on 2025-04-23 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentify', '0003_agent_illustration_agent_tier'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agent',
            options={'ordering': ['category', 'name']},
        ),
        migrations.AddField(
            model_name='agent',
            name='category',
            field=models.CharField(choices=[('content_creation', 'Content Creation'), ('communication', 'Communication'), ('automation', 'Automation'), ('ecommerce', 'E-commerce'), ('travel', 'Travel'), ('fitness_wellness', 'Fitness & Wellness'), ('education_learning', 'Education & Learning'), ('finance_investing', 'Finance & Investing'), ('home_lifestyle', 'Home & Lifestyle'), ('entertainment', 'Entertainment'), ('healthcare', 'Healthcare'), ('legal', 'Legal'), ('real_estate', 'Real Estate'), ('business', 'Business'), ('human_resources', 'Human Resources'), ('marketing', 'Marketing'), ('other', 'Other')], default='other', help_text='The category this agent belongs to.', max_length=50),
        ),
        migrations.AlterField(
            model_name='agent',
            name='tier',
            field=models.CharField(choices=[('basic', 'Basic'), ('pro', 'Pro'), ('advanced', 'Advanced')], default='basic', help_text='Access tier for this agent.', max_length=20),
        ),
    ]
